/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kartdroid;

import io.reactivex.rxjava3.core.Flowable;

public class App {
    public Flowable<String> getGreeting() {
        return Flowable.just("Hello world.");
    }

    public static void main(String[] args) {
        new App().getGreeting().subscribe(System.out::println).dispose();
    }
}
